// D4 German Translator - Translates German D4 terms to English
// Format: "German (English)"
// Auto-updated with scrape_complete_id_based.py data

// ============================================================================
// PARAGON GLYPH TRANSLATIONS
// ============================================================================
const glyphTranslations = {
  "Abschirmend": "Warding",
  "Absorbierer": "Imbiber",
  "Abyssal": "Abyssal",
  "Angeboren": "Innate",
  "Anrufung": "Invocation",
  "Apostel": "Apostle",
  "Aufgeladen": "Charged",
  "Aufopferung": "Sacrificial",
  "Ausbeuten": "Exploit",
  "Auslöscher": "Eliminator",
  "Ausweiden": "Disembowel",
  "Axe Bad Data": "Axe Bad Data",
  "Bann": "Bane",
  "Beidhändig": "Ambidextrous",
  "Beschwörer": "Conjurer",
  "Beschützer": "Protector",
  "Besonnen": "Canny",
  "Blutfresser": "Bloodfeeder",
  "Bluttrinker": "Blood-drinker",
  "Brodelnd": "Seething",
  "Dominieren": "Dominate",
  "Dunkelheit": "Darkness",
  "Effizienz": "Efficacy",
  "Eitern": "Fester",
  "Elektrifizieren": "Electrocute",
  "Elementarist": "Elementalist",
  "Entfesseln": "Unleash",
  "Entladen": "Fulminate",
  "Erde und Himmel": "Earth and Sky",
  "Essenz": "Essence",
  "Exhumierung": "Exhumation",
  "Explosiv": "Explosive",
  "Fackel": "Torch",
  "Falle": "Snare",
  "Ferne": "Ranger",
  "Fitness": "Fitness",
  "Flammenfresser": "Flamefeeder",
  "Fluidität": "Fluidity",
  "Frostfresser": "Frostfeeder",
  "Gebieter": "Arbiter ",
  "Geist": "Spirit",
  "Geißel": "Scourge",
  "Geschliffen": "Honed",
  "Gesetz": "Law",
  "Gestaltwandler": "Shapeshifter",
  "Gezackte Feder": "Jagged Plume",
  "Geübt": "Adept",
  "Golem": "Golem",
  "Grabhüter": "Gravekeeper",
  "Groll": "Ire",
  "Hackbeil": "Cleaver",
  "Haltung": "Poise",
  "Herausforderer": "Challenger",
  "Hinterhalt": "Ambush",
  "Hybris": "Hubris",
  "Hüter": "Keeper",
  "Inbrünstig": "Feverous",
  "Infusion": "Infusion",
  "Kampf": "Combat",
  "Klaue": "Talon",
  "Kolossal": "Colossal",
  "Konsum": "Consumption",
  "Kontrolle": "Control",
  "Kopfjäger": "Headhunter",
  "Krieger": "Warrior",
  "Kryopathie": "Cryopathy",
  "Körperlich": "Corporeal",
  "Lauffeuer": "Wildfire",
  "Macht": "Might",
  "Magier": "Mage",
  "Marschall": "Marshal",
  "Menagerist": "Menagerist",
  "Mensch": "Human",
  "Nachtpirscher": "Nightstalker",
  "Nähe": "Closer",
  "Poltern": "Rumble",
  "Pracht": "Resplendence",
  "Pyromane": "Pyromaniac",
  "Rache": "Revenge",
  "Rauferei": "Brawl",
  "Reißer und Klaue": "Fang and Claw",
  "Richter": "Judicator",
  "Ritual": "Ritual",
  "Scharfrichter": "Executioner",
  "Schleifen": "Hone",
  "Schlinger": "Guzzler",
  "Schändung": "Desecration",
  "Splitter": "Chip",
  "Stalagmit": "Stalagmite",
  "Stolz": "Pride",
  "Stromschlag": "Electrocution",
  "Taktiker": "Tactician",
  "Tektonisch": "Tectonic",
  "Territorial": "Territorial",
  "Torf": "Turf",
  "Tornado": "Twister",
  "Totenbeleber": "Deadraiser",
  "Tödliche Flinkheit": "Mortal Draw",
  "Unerschrocken": "Undaunted",
  "Verfolger": "Tracker",
  "Verringern": "Diminish",
  "Verschlagen": "Devious",
  "Verstärken": "Amplify",
  "Verstärkt": "Reinforced",
  "Verzauberer": "Enchanter",
  "Vielseitigkeit": "Versatility",
  "Waffenmeister": "Weapon Master",
  "Werbär": "Werebear",
  "Werwolf": "Werewolf",
  "Wildnis": "Wilds",
  "Winter": "Winter",
  "Wächter": "Sentinel",
  "Zermalmer": "Crusher",
  "Zerstörung": "Destruction",
  "Zorn": "Wrath",
  "Übertreffen": "Outmatch",
};

// ============================================================================
// UNIQUE/MYTHIC ITEM TRANSLATIONS
// ============================================================================
const itemTranslations = {
  "&quot;Marsch der Goblins&quot;-Emblem": "March of the Goblins Emblem",
  "Aaskette": "Carrion Chain",
  "Abenteurerhandschuhe": "Adventurer's Gloves",
  "Abstimmungsstein: Brechen": "Tuning Stone: Breaking",
  "Abstimmungsstein: Dauer": "Tuning Stone: Duration",
  "Abstimmungsstein: Durchbohren": "Tuning Stone: Piercing",
  "Abstimmungsstein: Greifen": "Tuning Stone: Gripping",
  "Abstimmungsstein: Initiative": "Tuning Stone: Initiative",
  "Abstimmungsstein: Mehrfachschuss": "Tuning Stone: Multishot",
  "Abstimmungsstein: Registrierter Schaden": "Tuning Stone: Registered Damage",
  "Abstimmungsstein: Taktisch": "Tuning Stone: Tactical",
  "Abstimmungsstein: Voluminös": "Tuning Stone: Voluminous",
  "Abstruses Siegel": "Abstruse Sigil",
  "Adlereffizienz": "Eagle Efficiency",
  "Adlerfinesse": "Eagle Finesse",
  "Adlerinnovation": "Eagle Innovation",
  "Adlerzunahmen": "Eagle Augments",
  "Aegis": "Aegis",
  "Agilitätszunahmen": "Agile Augments",
  "Akarats Lied": "Akarat's Song",
  "Alchemistenkontrolle": "Alchemist Control",
  "Aldkin-Truhe": "Aldkin Cache",
  "Aldkin-Truhe der Vollendung": "Aldkin Masterworking Cache",
  "Allwesenskette": "All-Being Chain",
  "Alptraumkugel": "Nightmare Orb",
  "Amazonenband": "Amazon Band",
  "Amulett": "Amulet",
  "Anführer­handschuhe": "Captain's Gloves",
  "Anregungskreis": "Innervation Circle",
  "Archaische Beckenhaube": "Primal Bascinet",
  "Archaische Brustplatte": "Primal Breastplate",
  "Archaische Kettengamaschen": "Primal Chausses",
  "Archaische Panzerhandschuhe": "Primal Gauntlets",
  "Archaische Sabatons": "Primal Sabatons",
  "Archonbeinschienen": "Archon Greaves",
  "Archondiechlinge": "Archon Faulds",
  "Archonhelm": "Archon Helm",
  "Archonrüstung": "Archon Armor",
  "Archon­panzer­handschuhe": "Archon Gauntlets",
  "Arsenalfinesse (Vermächtnis)": "Arsenal Finesse (Legacy)",
  "Ashavas Beute": "Ashava's Spoils",
  "Assassinenzunahmen": "Assassin Augments",
  "Aufsteigender Kampfstab": "Ascendant Quarterstaff",
  "Auge des Adlers": "Eagle's Eye",
  "Auge des Axolotls": "Axolotl's Eye",
  "Auge des Gorillas": "Gorilla's Eye",
  "Auge des Jaguars": "Jaguar's Eye",
  "Auge des Löwen": "Lion's Eye",
  "Auge des Ozelots": "Ocelot's Eye",
  "Aurainnovation": "Aura Innovation",
  "Ausrüstungstruhe": "Equipment Cache",
  "Ausrüstungstruhe: Dritte Reise": "Third Journey Equipment Cache",
  "Ausrüstungstruhe: Erste Reise": "First Journey Equipment Cache",
  "Ausrüstungstruhe: Vierte Reise": "Fourth Journey Equipment Cache",
  "Ausrüstungstruhe: Zweite Reise": "Second Journey Equipment Cache",
  "Außergewöhnliche Beinlinge": "Exceptional Leggings",
  "Außergewöhnliche Rüstung": "Exceptional Armor",
  "Außergewöhnliche Stiefel": "Exceptional Boots",
  "Außergewöhnlicher Helm": "Exceptional Helm",
  "Außer­gewöhnliche Handschuhe": "Exceptional Gloves",
  "Axe Bad Data": "Axe Bad Data",
  "Azmodans Beute": "Azmodan's Spoils",
  "Balläster": "Cranequin",
  "Band": "Band",
  "Barbarenbewegung": "Barbarian Motion",
  "Barbarenbresche": "Barbarian Breach",
  "Barbarenerholung": "Barbarian Recovery",
  "Barbareninnovation": "Barbarian Innovation",
  "Barbarenkontrolle": "Barbarian Control",
  "Barbarenschutz (Vermächtnis)": "Barbarian Protection (Legacy)",
  "Barbaren­strategie": "Barbarian Strategy",
  "Bartaxt": "Bearded Axe",
  "Basiszunahmen – Präzision": "Marksman Augments — Basic",
  "Bedingungsrunen-Truhe": "Condition Runes Cache",
  "Behänder Stab": "Nimble Staff",
  "Beinlinge des Unheilvollen Vorhabens": "Breeches of Baleful Intent",
  "Beinschutz": "Pants",
  "Beinschutz des Untergangs": "Doom Cuisses",
  "Belagerungsbogen": "Siege Bow",
  "Belohnungstruhe der Horadrim": "Horadric Reward Cache",
  "Benommenheits­kontrolle": "Daze Control",
  "Berserkerinnovation": "Berserking Innovation",
  "Berserkermodusfinesse": "Berserking Finesse",
  "Berührung des Zauberers": "Wizard's Touch",
  "Beschwörungseffizienz": "Conjuration Efficiency",
  "Beschwörungsfinesse": "Conjuration Finesse",
  "Beschwörungsglück": "Conjuration Fortune",
  "Beschwörungstruhe Grigoires": "Grigoire Summoning Cache",
  "Beschwörungstruhe Varshans": "Varshan Summoning Cache",
  "Beschwörungstruhe der Bestie im Eis": "Beast in the Ice Summoning Cache",
  "Beschwörungstruhe des Champions": "Champion's Summoning Cache",
  "Beschwörungstruhe des Schlächters": "Slayer's Summoning Cache",
  "Beschwörungstruhe des Zerstörers": "Destroyer's Summoning Cache",
  "Beschwörungstruhe: Dritte Reise": "Third Journey Summoning Cache",
  "Beschwörungstruhe: Vierte Reise": "Fourth Journey Summoning Cache",
  "Beschwörungszunahmen": "Conjuration Augments",
  "Bestienbrecher": "Beastbreaker",
  "Beute Sanktuarios": "Spoils of Sanctuary",
  "Beute der Habgier": "Avarice's Spoils",
  "Beute des Eroberers der Reiche": "Spoils of the Realm Conqueror",
  "Beute des Wandelnden Todes": "Wandering Death's Spoils",
  "Beutebeobachter": "Preywatcher",
  "Beuteglück II": "Looter's Luck II",
  "Bezaubernde Stangenwaffe": "Charming Polearm",
  "Bezauberter Ring": "Ensorcelled Ring",
  "Biss der Schlange": "Serpent's Bite",
  "Blasses Zeichen": "Pale Mark",
  "Blick des Hasses": "Hatred's Gaze",
  "Blick des Jaguars": "Jaguar's Gaze",
  "Blitzzunahmen": "Lightning Augments",
  "Blutbeständigkeit": "Blood Endurance",
  "Blutesschmuck": "Adorned-in-blood",
  "Blutfinesse": "Blood Finesse",
  "Blutiger Zauber": "Bloody Charm",
  "Blutiges Elfenbein": "Blood-tinged Ivory",
  "Blutinnovation": "Blood Innovation",
  "Blutknochenbeinverstärkung": "Blood Bone Leg Reinforcements",
  "Blutknochen­beinverstärkung": "Blood Bone Leg Reinforcements",
  "Blutsauger": "Bloodsucker",
  "Blutstill­reif": "Blood-staunch Hoop",
  "Blutsucherwaffentruhe": "Blood Seeker's Weapon Cache",
  "Blutsucher­waffentruhe": "Blood Seeker's Weapon Cache",
  "Blutungsinnovation": "Bleed Innovation",
  "Blutungszunahmen": "Bleed Augments",
  "Blutzunahmen": "Blood Augments",
  "Boshafter Blick": "Malefic Gaze",
  "Bossbeschwörung": "Boss Summoning",
  "Bossbeschwörungs­truhe": "Boss Summoning Cache",
  "Botenausrüstung der Eisenwölfe": "Iron Wolves' Messenger Gear",
  "Botenkiste der Eisenwölfe": "Iron Wolves' Messenger Case",
  "Brillanz": "Brilliance",
  "Brutalisten­innovation": "Brute Innovation",
  "Bullova": "Bullova",
  "Buriza-Do Kyanon": "Buriza-Do Kyanon",
  "Chaosmacht": "Chaotic Power",
  "Chaotische Abklingzeiten": "Chaotic Cooldowns",
  "Chaotische Granaten": "Chaotic Grenades",
  "Chepesch": "Khopesh",
  "Defensivaspekte": "Defensive Aspects",
  "Demolierungsfinesse": "Demolition Finesse",
  "Dienerfinesse": "Minion Finesse",
  "Dienerzunahmen": "Minion Augments",
  "Dolchmesser des Todes": "Death's Dirk",
  "Dornenarmee": "Thorn Army",
  "Dornenkörper": "Thorn Body",
  "Drachendorn": "Dragon Spine",
  "Dreimetallener Ring": "Trimetal Ring",
  "Druidenbewegung": "Druid Motion",
  "Druidenkräftigung": "Druid Invigoration",
  "Dschungeldorn": "Jungle Thorn",
  "Dschungelspalter": "Jungle Cleaver",
  "Dunkle Ältesten-Axt": "Dark Elder Axe",
  "Dämonenklinge": "Demonblade",
  "Ebenenzunahmen": "Plains Augments",
  "Echokreis": "Echo Circle",
  "Ectors Materialtasche": "Ector's Bag of Materials",
  "Effektrunen-Truhe": "Effect Runes Cache",
  "Eignungseffizienz": "Fitness Efficiency",
  "Einschlaghammer": "Impact Hammer",
  "Eiskaltes Herz": "Frigid Heart",
  "Elegante Gleve": "Elegant Glaive",
  "Elegante Stangenwaffe": "Elegant Polearm",
  "Elementarfinesse – Nacht": "Elemental Finesse — Night",
  "Elementarfinesse – Tag": "Elemental Finesse — Day",
  "Elementarkontrolle": "Elemental Control",
  "Elementarwoge – Nacht": "Elemental Surge — Night",
  "Elementarwoge – Tag": "Elemental Surge — Day",
  "Elemente des Erzfeindes": "Elements of Nemesis",
  "Ende des Kaisers": "Emperor's End",
  "Energiestab": "Energy Staff",
  "Enigmawürfel": "Enigma Cube",
  "Enthauptungsinnovation": "Execution Innovation",
  "Entladung": "Fulmination",
  "Entweihte Finesse": "Profane Finesse",
  "Entweihte Innovation": "Profane Innovation",
  "Entweihter Käfig": "Profane Cage",
  "Entweihung der Toten": "Defile the Dead",
  "Erdenbad": "Bathed-in-earth",
  "Erdfinesse": "Earth Finesse",
  "Erdzunahmen": "Earth Augments",
  "Eskalationssiegel": "Escalation Sigil",
  "Estuarisches Symbol": "Estuarian Symbol",
  "Etsechekes Gehstock": "Etsecheke's Walking Stick",
  "Experten-Härtungsset": "Expert Tempering Kit",
  "Fallenexpertise": "Trap Expertise",
  "Fallenzunahmen": "Trap Augments",
  "Fanatikereffizienz": "Zealot Efficiency",
  "Fanatikerfinesse": "Zealot Finesse",
  "Fanatikerinnovation": "Zealot Innovation",
  "Fanatikerzunahmen": "Zealot Augments",
  "Faulige Seelensammlung": "Putrid Soul Collection",
  "Feindliches Siegel": "Inimical Seal",
  "Fenster der Schöpfung": "Window to Creation",
  "Fernhalten": "Back Off!",
  "Filigraner Silberbogen": "Silver Filigree Bow",
  "Finaldungeontruhe – Rang IV": "Rank IV Capstone Cache",
  "Finesse des Wächters": "Guardian Finesse",
  "Fingerkranz": "Finger-wreath",
  "Flammengleve": "Flame Glaive",
  "Flammenschwert": "Flammard",
  "Fokus der Gerächten": "Focus of the Avenged",
  "Folterstab": "Torment Staff",
  "Freund des Sumpfes": "Friend of the Bog",
  "Frostfinesse": "Frost Finesse",
  "Frostkäfig": "Frost Cage",
  "Frostzunahmen": "Frost Augments",
  "Frostzunahmen – Eingefroren": "Frost Augments —  Frozen",
  "Furorzunahmen": "Furious Augments",
  "Fünffach geschmiedetes Siegel": "Pentaforged Seal",
  "Fürst Zirs persönlicher Vorrat": "Lord Zir's Personal Stash",
  "Gaunerfinesse": "Scoundrel Finesse",
  "Gedankenkranz": "Mind Wreath",
  "Geehrtes Relikt": "Honored Relic",
  "Gefangenenstein": "Captive Stone",
  "Gefiederte Stangenwaffe": "Feathered Polearm",
  "Gefährteneffizienz": "Companion Efficiency",
  "Gefährten­innovation": "Companion Innovation",
  "Gefährten­zunahmen": "Companion Augments",
  "Geheimnisvolle große Archetyp-Truhe ": "Mystery Greater Archetype Cache ",
  "Gehörnter Schlägel": "Horned Cudgel",
  "Geister-Kampfstab": "Spirit Quarterstaff",
  "Geisterstunde": "Witching Hour",
  "Geisteskampf­kern": "Spiritomachy Core",
  "Geistgeborenen­beständigkeit": "Spiritborn Endurance",
  "Geistgeborenen­bewegung": "Spiritborn Motion",
  "Geistgeborenen­entschlossenheit": "Spiritborn Resolve",
  "Geistgeborenen­erholung": "Spiritborn Recovery",
  "Geistgeborenen­schutz": "Spiritborn Guard",
  "Geringe Elemente des Erzfeindes": "Lesser Elements of Nemesis",
  "Geschenk des Baumes": "Gift of the Tree",
  "Geschickte Finesse": "Skillful Finesse",
  "Geschmolzener Lotus": "Molten Lotus",
  "Geschwärzte Essenz": "Blackened Essence",
  "Geschärfte Finesse": "Sharpened Finesse",
  "Geschärfte Stangenwaffe": "Sharpened Polearm",
  "Gestaltwandelfinesse": "Shapeshifting Finesse",
  "Gestaltwandel­beständigkeit": "Shapeshifting Endurance",
  "Gewobener Kampfstab": "Woven Quarterstaff",
  "Gezackte Axt": "Serrated Axe",
  "Gezackter Schnitter": "Toothed Reaper",
  "Gezackter Spalter": "Serrated  Cleaver",
  "Gileons Gebräu": "Gileon's Brew",
  "Glorreicher Stab": "Glorious Staff",
  "Goldene Stangenwaffe": "Golden Polearm",
  "Goldener Kampfstab": "Golden Quarterstaff",
  "Goldgleve": "Golden Glaive",
  "Gorillaeffizienz": "Gorilla Efficiency",
  "Gorillafinesse": "Gorilla Finesse",
  "Gorillainnovation": "Gorilla Innovation",
  "Gorillazunahmen": "Gorilla Augments",
  "Grabes­bollwerk": "Grave Bulwark",
  "Grabkammer-Hinrichter": "Sepulcher Executor",
  "Grauensstachel": "Dreadspike",
  "Grausige Trophäe": "Grisly Trophy",
  "Griff des Hasses": "Hatred's Grasp",
  "Grimoire der Geisterstunde": "Witching Hour Grimoire",
  "Grimoire der Stimme der Sterne": "Voice of the Stars Grimoire",
  "Grimoire des Freunds des Sumpfes": "Friend of the Bog Grimoire",
  "Grimoire des Gedankenkranzes": "Mind Wreath Grimoire",
  "Grimoire des Mondlichtschutzes": "Moonlight Ward Grimoire",
  "Grimoire des Staubsteins": "Dust Stone Grimoire",
  "Große Adlertruhe ": "Greater Eagle Cache ",
  "Große Alchemistentruhe ": "Greater Alchemist Cache ",
  "Große Aldkin-Truhe": "Grand Aldkin Cache",
  "Große Amulettsammlung": "Greater Collection of Amulets",
  "Große Beinschützer­sammlung": "Greater Collection of Leg Guards",
  "Große Berserkertruhe ": "Greater Berserker Cache ",
  "Große Beschwörungstruhe ": "Greater Conjuration Cache ",
  "Große Bluttruhe ": "Greater Blood Cache ",
  "Große Brustpanzer­sammlung": "Greater Collection of Chestplates",
  "Große Chaossammlung": "Greater Collection of Chaos",
  "Große Dungeonschlüssel­sammlung": "Greater Collection of Dungeon Keys",
  "Große Einhandwaffen­sammlung": "Greater Collection of One-handed Weapons",
  "Große Elemente der Hexenmacht": "Greater Elements of Witchcraft",
  "Große Erdtruhe ": "Greater Earth Cache ",
  "Große Erwachte Beute": "Greater Awakened Spoils",
  "Große Fanatikertruhe ": "Greater Zealot Cache ",
  "Große Frosttruhe ": "Greater Frost Cache ",
  "Große Goldsammlung": "Greater Collection of Gold",
  "Große Gorillatruhe ": "Greater Gorilla Cache ",
  "Große Herbeirufungstruhe ": "Greater Summoning Cache ",
  "Große Jaguartruhe ": "Greater Jaguar Cache ",
  "Große Jüngertruhe ": "Greater Disciple Cache ",
  "Große Knochentruhe ": "Greater Bone Cache ",
  "Große Kopfschutz­sammlung": "Greater Collection of Helms",
  "Große Materialsammlung": "Greater Collection of Materials",
  "Große Meuchlertruhe ": "Greater Cutthroat Cache ",
  "Große Mittwinterbeute": "Greater Midwinter Spoils",
  "Große Mittwinter­tasche ": "Greater Midwinter Purse ",
  "Große Molochtruhe ": "Greater Juggernaut Cache ",
  "Große Obduzit-Truhe I": "Large Obducite Cache I",
  "Große Obduzit-Truhe II": "Large Obducite Cache II",
  "Große Panzerhandschuh­sammlung": "Greater Collection of Gauntlets",
  "Große Präzisionstruhe ": "Greater Marksman Cache ",
  "Große Pyromanietruhe ": "Greater Pyromancy Cache ",
  "Große Raheir-Truhe": "Grand Raheir Cache",
  "Große Ranglistentruhe": "Greater Ranking Cache",
  "Große Raufboldtruhe ": "Greater Brawler Cache ",
  "Große Reisetruhe": "Greater Journey Cache",
  "Große Richtertruhe ": "Greater Judicator Cache ",
  "Große Ringsammlung": "Greater Collection of Rings",
  "Große Schattentruhe ": "Greater Shadow Cache ",
  "Große Schatztasche": "Greater Treasure Bag",
  "Große Schatztasche ": "Greater Treasure Bag ",
  "Große Schlächtertruhe ": "Greater Slayer Cache ",
  "Große Schocktruhe ": "Greater Shock Cache ",
  "Große Stiefelsammlung": "Greater Collection of Boots",
  "Große Sturmtruhe ": "Greater Storm Cache ",
  "Große Subo-Truhe": "Grand Subo Cache",
  "Große Tausendfüßertruhe ": "Greater Centipede Cache ",
  "Große Truhe der Vollendung": "Greater Masterwork Cache",
  "Große Truhe des Fallenstellers ": "Greater Trapper Cache ",
  "Große Truhe voller Edelsteinfragmente": "Greater Cache of Gem Fragments",
  "Große Varyana-Truhe": "Grand Varyana Cache",
  "Große Werbärentruhe ": "Greater Werebear Cache ",
  "Große Werwolftruhe ": "Greater Werewolf Cache ",
  "Große Zweihandwaffen­sammlung": "Greater Collection of Two-Handed Weapons",
  "Große Ödländertruhe ": "Greater Wastelander Cache ",
  "Großherz­band": "Greatheart Band",
  "Großschwert des Gargoyles": "Gargoyle Greatsword",
  "Grässliche Zunahmen": "Dreadful Augments",
  "Hammer der Reue": "Penitent Hammer",
  "Handschuhe": "Gloves",
  "Handschuh­kiste des Anführers": "Captain's Glove Case",
  "Handwerk": "Crafting",
  "Handwerkstruhe des Champions": "Champion's Crafting Cache",
  "Handwerkstruhe des Schlächters": "Slayer's Crafting Cache",
  "Handwerkstruhe des Zerstörers": "Destroyer's Crafting Cache",
  "Handwerkstruhe: Dritte Reise": "Third Journey Crafting Cache",
  "Handwerkstruhe: Vierte Reise": "Fourth Journey Crafting Cache",
  "Haufen vampirischen Schuhwerks": "Pile of Vampiric Footwear",
  "Hautreißer": "Skinripper",
  "Heilige Waffentruhe der Triune": "Sacred Triune Arms Cache",
  "Herausforderertruhe der Dunklen Zitadelle": "Dark Citadel Challenger's Cache",
  "Herrschaftskette": "Dominion Chain",
  "Herz des Hasses": "Hatred's Heart",
  "Himmelszunahmen": "Sky Augments",
  "Höllenhauer": "Hell's Fang",
  "Höllenhordenkompass": "Infernal Hordes Compass",
  "Hügelstein": "Cairnstone",
  "Infusionsüberfluss": "Imbuement Abundance",
  "Irdenes Band": "Earthend Band",
  "Jade-Armbrust": "Jade Crossbow",
  "Jade-Macuahuitl": "Jade Macuahuitl",
  "Jadegleve": "Jade Glaive",
  "Jadehaken": "Jade Hook",
  "Jaderelikt": "Jade Relic",
  "Jade­zauberstab": "Jade Wand",
  "Jagdmedaille": "Hunt Medal",
  "Jaguareffizienz": "Jaguar Efficiency",
  "Jaguarfinesse": "Jaguar Finesse",
  "Jaguarinnovation": "Jaguar Innovation",
  "Jaguarschneide": "Jaguar's Razor",
  "Jaguarzunahmen": "Jaguar Augments",
  "Jambiya": "Jambiya",
  "Jägerbeharrlichkeit (Vermächtnis)": "Rogue Persistence (Legacy)",
  "Jägerbewegung": "Rogue Motion",
  "Jägererholung": "Rogue Recovery",
  "Jägerinnovation": "Rogue Innovation",
  "Jägerkräftigung": "Rogue Invigoration",
  "Jägertarnung": "Rogue Cloaking",
  "Jüngereffizienz": "Disciple Efficiency",
  "Jüngerinnovation": "Disciple Innovation",
  "Jüngerzunahmen": "Disciple Augments",
  "Kannibalenbeil": "Cannibal's Chopper",
  "Kappe": "Cap",
  "Kernzunahmen – Barbar": "Core Augments — Barbarian",
  "Kernzunahmen – Präzision": "Marksman Augments — Core",
  "Kesseldruck": "Pressurized Steam",
  "Kette": "Chain",
  "Kettenhammer": "Chain Hammer",
  "Kindschal": "Khanjali",
  "Kiste mit Vampirbeute": "Crate of Vampire Spoils",
  "Klappernde Knochen": "Rattling Bones",
  "Klinge des Ghulkönigs": "Ghoul King's Blade",
  "Knochenbogen der Schlange": "Serpent's Bone Bow",
  "Knochenbrecher": "Bonebreaker",
  "Knochenfinesse": "Bone Finesse",
  "Knocheninnovation": "Bone Innovation",
  "Knochenklinge": "Bone Blade",
  "Knochenschild": "Bone Shield",
  "Knochensense": "Bone Scythe",
  "Knochenzauberstab": "Bone Wand",
  "Knochenzunahmen": "Bone Augments",
  "Knochenzwirnhelm": "Boneweave Helm",
  "Knochenzwirnrüstung": "Boneweave Armor",
  "Knochenzwirntreter": "Boneweave Treads",
  "Knochenzwirn­diechlinge": "Boneweave Faulds",
  "Knochenzwirn­panzer­handschuhe": "Boneweave Gauntlets",
  "Knochen­schuppen­schild": "Bonescale Shield",
  "Knöchelkeule": "Knockhand Club",
  "Kontrafluch­schutz": "Contracurse Ward",
  "Krakenklinge": "Octopian Edge",
  "Kreis": "Circle",
  "Kreis des Unheilvollen Vorhabens": "Loop of Baleful Intent",
  "Kreuzaxt": "Cross Axe",
  "Kriegsherrnrüstung": "Warlord Plate",
  "Kriegsherrnstiefel": "Warlord Boots",
  "Kriegsherrn­beinplatten": "Warlord Leg Plates",
  "Kriegsherrn­platten­handschuhe": "Warlord Gauntlets",
  "Kriegslanze": "War Crest",
  "Kriegsrats­band": "Warcouncil Band",
  "Kriegsschleuder": "Warcaster",
  "Kriegstruhe der Triune": "Triune War Chest",
  "Kriegsversammlung-Totem": "Warmuster Totem",
  "Kristallgroßschwert": "Crystal Greatsword",
  "Krokodilsauge": "Crocodilian Eye",
  "Krone des Unheilvollen Vorhabens": "Crown of Baleful Intent",
  "Kryptische Partisane": "Cryptic Partizan",
  "Kräutersammler­schatz der Eisenwölfe": "Iron Wolves' Herbalist Hoard",
  "Kästchen der Eisenwölfe": "Iron Wolves Vanity Chest",
  "Königliche Knochenklinge": "Royal Boneblade",
  "Lebensreif": "Lifeward Loop",
  "Legendary Test Amulet": "Legendary Test Amulet",
  "Legendary Test Axe1H": "Legendary Test Axe1H",
  "Legendary Test Axe2H": "Legendary Test Axe2H",
  "Legendary Test Boots": "Legendary Test Boots",
  "Legendary Test Bow": "Legendary Test Bow",
  "Legendary Test Chest": "Legendary Test Chest",
  "Legendary Test Crossbow2H": "Legendary Test Crossbow2H",
  "Legendary Test Dagger1H": "Legendary Test Dagger1H",
  "Legendary Test Focus": "Legendary Test Focus",
  "Legendary Test Gloves": "Legendary Test Gloves",
  "Legendary Test Helm": "Legendary Test Helm",
  "Legendary Test Mace1H": "Legendary Test Mace1H",
  "Legendary Test Mace2H": "Legendary Test Mace2H",
  "Legendary Test Pants": "Legendary Test Pants",
  "Legendary Test Polearm2H": "Legendary Test Polearm2H",
  "Legendary Test Ring": "Legendary Test Ring",
  "Legendary Test Scythe1H": "Legendary Test Scythe1H",
  "Legendary Test Scythe2H": "Legendary Test Scythe2H",
  "Legendary Test Shield": "Legendary Test Shield",
  "Legendary Test Staff2H": "Legendary Test Staff2H",
  "Legendary Test Sword1H": "Legendary Test Sword1H",
  "Legendary Test Sword2H": "Legendary Test Sword2H",
  "Legendary Test Totem": "Legendary Test Totem",
  "Legendary Test Wand": "Legendary Test Wand",
  "Legendäre Arkana": "Legendary Arcana",
  "Legendäre Goblin-Runensammlung": "Goblins Collection of Legendary Runes",
  "Legendäre Goblin-Tribute der Unterstadt von Kurast": "Goblin's Legendary Kurast Undercity Tributes",
  "Legendäre Runentruhe der Urahnen": "Ancestors' Legendary Runes Cache",
  "Legendäre Runentruhe des Goblins": "Goblin's Legendary Rune Cache",
  "Legendäre Urahnen-Tribute der Unterstadt von Kurast": "Ancestors' Legendary Kurast Undercity Tributes",
  "Legendäre Zirkelkiste": "Legendary Coven Crate",
  "Legendäres Geschenk der Urahnen": "Legendary Gift from the Ancestors",
  "Legendäres Goblingeschenk": "Legendary Goblin Gift",
  "Leitstein: Adrenalinschub": "Governing Stone: Flash of Adrenaline",
  "Leitstein: Auflauern": "Governing Stone: Bushwhack",
  "Leitstein: Autoverteidigung": "Governing Stone: Autodefense",
  "Leitstein: Glühwürmchen": "Governing Stone: Firefly",
  "Leitstein: Orkan": "Governing Stone: Tempest",
  "Leitstein: Pfählen": "Governing Stone: Impale",
  "Leuchtende Schatztasche": "Radiant Treasure Bag",
  "Lichklinge": "Lich Blade",
  "Limbische Grenze": "Limbic Boundary",
  "Lächeln des Axolotls": "Axolotl's Smile",
  "Löwenring": "Leonine Loop",
  "Malaphische Kurve": "Malaphic Curve",
  "Manaerfüllte Beschwörungen": "Mana Infused Conjurations",
  "Marodeursaxt": "Marauder Axe",
  "Marsch des Hasses": "Hatred's March",
  "Mehr Horadrische Phiolen": "More Horadric Phials",
  "Meisterwerks­metall": "Mastercraft Metal",
  "Meuchelfinesse": "Cutthroat Finesse",
  "Mittwinter-Runen­sammlung": "Midwinter Collection of Runes",
  "Mobilitätsaspekte": "Mobility Aspects",
  "Molocheffizienz": "Juggernaut Efficiency",
  "Molochfinesse (DNS)": "Juggernaut Finesse (DNS)",
  "Molochinnovation": "Juggernaut Innovation",
  "Molochzunahmen": "Juggernaut Augments",
  "Mondlicht": "Moonlight",
  "Mondlichtschutz": "Moonlight Ward",
  "Monsunsaum": "Monsoon Line",
  "Murls Obolustasche": "Murl's Bag of Obols",
  "Murls überwältigende Obolustasche": "Murl's Bag of Overwhelming Obols",
  "Münztasche des Barons": "Baron's Bag of Coin",
  "Nahantu-Schatz­tasche": "Nahantu Treasure Bag",
  "Naturmagie-Innovation": "Nature Magic Innovation",
  "Naturmagiewand": "Nature Magic Wall",
  "Natürliche Bewegung": "Natural Motion",
  "Natürliche Finesse": "Natural Finesse",
  "Natürliche Schemata": "Natural Schemes",
  "Natürlicher Widerstand": "Natural Resistance",
  "Nessel-Streitkolben": "Nettle Mace",
  "Niedereisen": "Neathiron",
  "Nobler Schlitzer": "Noble Slice",
  "Obsidianklinge": "Obsidian Blade",
  "Obsidiantotem": "Obsidian Totem",
  "Ohrenbetäubender Chor": "Deafening Chorus",
  "Opfersichel": "Sacrificial Sickle",
  "Opulente Manschette": "Lush Cuff",
  "PH Tempering Template": "PH Tempering Template",
  "PTR Cache - Chaos Armor - Boots": "PTR Cache - Chaos Armor - Boots",
  "PTR Cache - Chaos Armor - Chest Armor": "PTR Cache - Chaos Armor - Chest Armor",
  "PTR Cache - Chaos Armor - Gloves": "PTR Cache - Chaos Armor - Gloves",
  "PTR Cache - Chaos Armor - Helms": "PTR Cache - Chaos Armor - Helms",
  "PTR Cache - Chaos Armor - Legs": "PTR Cache - Chaos Armor - Legs",
  "PTR-Truhe – Generische Härtungsanleitungen": "PTR Cache - Generic Temper Manuals",
  "PTR-Truhe – Horadrische Juwelen": "PTR Cache - Horadric Jewels",
  "PTR-Truhe – Höllenkompasse": "PTR Cache - Infernal Compasses",
  "PTR-Truhe – Klassenspezifische Härtungsanleitungen": "PTR Cache - Class Temper Manuals",
  "PTR-Truhe – Runen der Anrufung": "PTR Cache - Runes of Invocation",
  "PTR-Truhe – Runen des Rituals": "PTR Cache - Runes of Ritual",
  "PTR-Truhe – Saisonale Währung": "PTR Cache - Seasonal Activity Items",
  "PTR-Truhe – Siegel der Alptraum-Eskalation": "PTR Cache - Nightmare Escalation Sigils",
  "PTR-Truhe – Tribute": "PTR Cache - Tributes",
  "PTR-Truhe – Unterschlupfschlüssel": "PTR Cache - Lair Keys",
  "PTR-Truhe – Zufällige legendäre Gegenstände": "PTR Cache - Random Legendaries",
  "Paket mit Ghulhauthandschuhen": "Pack of Ghoul-Skin Gloves",
  "Paket mit Ghulhaut­handschuhen": "Pack of Ghoul-Skin Gloves",
  "Paladinbeharrlichkeit": "Paladin Perseverance",
  "Paladinbewegung": "Paladin Motion",
  "Paladinerholung": "Paladin Recovery",
  "Paladinschutz": "Paladin Guard",
  "Paladin­entschlossenheit": "Paladin Resolve",
  "Panzergleve": "Armored Glaive",
  "Panzer­handschuhe der Verdammnis": "Doom Gauntlets",
  "Panzer­handschuhe des Unheilvollen Vorhabens": "Gauntlets of Baleful Intent",
  "Parashu": "Parashu",
  "Pareidolie­ring": "Pareidolic Ring",
  "Perplexe Rundung": "Perplex Round",
  "Persönliche Habe eines Blutsuchers": "Blood Seekers Personal Effects",
  "Prahlertruhe": "Braggart's Cache",
  "Prismatische Zunahmen": "Prismatic Augments",
  "Pryms Geschenk": "Prym's Gift",
  "Pryms Tasche der Glanzstücke": "Prym's Bag of Shiny",
  "Präzisionsfinesse": "Marksman Finesse",
  "Pyromanie-Beständigkeit": "Pyromancy Endurance",
  "Pyromanie-Finesse": "Pyromancy Finesse",
  "Pyromaniezunahmen": "Pyromancy Augments",
  "Pyromaniezunahmen – Feurig": "Pyromancy Augments —  Fiery",
  "Que-Hegan-Stahl": "Que-Hegan Steel",
  "Raheir-Truhe": "Raheir Cache",
  "Raheir-Truhe der Vollendung": "Raheir Masterworking Cache",
  "Raufboldeffizienz": "Brawling Efficiency",
  "Raufboldzunahmen": "Brawling Augments",
  "Regentenhelm": "Sovereign Helm",
  "Regentenrüstung": "Sovereign Mail",
  "Regentenstulpen": "Sovereign Vambraces",
  "Regententassetten": "Sovereign Tassets",
  "Regenten­beinschienen": "Sovereign Greaves",
  "Reif": "Choker",
  "Reinkarnations­klinge": "Rebirth Edge",
  "Reptilstab": "Reptilian Staff",
  "Ressourcenaspekte": "Resource Aspects",
  "Richtereffizienz": "Judicator Efficiency",
  "Richterfinesse": "Judicator Finesse",
  "Richterinnovation": "Judicator Innovation",
  "Richterzunahmen": "Judicator Augments",
  "Ring": "Ring",
  "Ring des Anbeters": "Worshipper's Ring",
  "Ring des Steinbrechers": "Quarrier's Ring",
  "Ritual-Kampfstab": "Ritual Quarterstaff",
  "Ritualdolch": "Ritual Dagger",
  "Ritualstab": "Ritual Staff",
  "Runenhandschuhe": "Runic Gloves",
  "Runenhose": "Runic Leggings",
  "Runenkappe": "Runic Skullcap",
  "Runenkettenhemd": "Runic Mail",
  "Runenkugel": "Runic Orb",
  "Runenstab": "Runic Staff",
  "Runenstollen": "Runic Cleats",
  "Rückgrat": "Spinal",
  "Rüstzeug der Eisenwölfe": "Iron Wolves' Armory",
  "Rüstzeug des Blutfürsten": "Blood Lord's Armory",
  "Rüstzeugtresor der Eisenwölfe": "Iron Wolves' Armory Safe",
  "Sack mit vampirischen Torques": "Sack of Vampiric Torques",
  "Sagaris": "Sagaris",
  "Schamanistischer Reif": "Shamanistic Hoop",
  "Schaman­istischer Stab": "Shamanistic Staff",
  "Scharfe Gleve": "Sharp Glaive",
  "Scharfrichter der Ketzer": "Heretic's Executioner",
  "Schattenfinesse": "Shadow Finesse",
  "Schattenzunahmen – Enthauptung": "Shadow Augments — Execution",
  "Schattenzunahmen – Verfall": "Shadow Augments — Decay",
  "Schatztasche": "Treasure Bag",
  "Schicker Kampfstab": "Fancy Quarterstaff",
  "Schlachtbogen": "Battle Bow",
  "Schlagender Kampfstab": "Smashing Quarterstaff",
  "Schlangenaxt": "Snake Axe",
  "Schlangenstein": "Serpent Stone",
  "Schlund des Tausendfüßers": "Centipede's Maw",
  "Schlächterfinesse": "Slayer's Finesse",
  "Schmiedetruhe": "Smithy Cache",
  "Schmucktruhe – Amethyst": "Amethyst Jewelry Cache",
  "Schmucktruhe – Diamant": "Diamond Jewelry Cache",
  "Schmucktruhe – Rubin": "Ruby Jewelry Cache",
  "Schmucktruhe – Saphir": "Sapphire Jewelry Cache",
  "Schmucktruhe – Schädel": "Skull Jewelry Cache",
  "Schmucktruhe – Smaragd": "Emerald Jewelry Cache",
  "Schmucktruhe – Topas": "Topaz Jewelry Cache",
  "Schneller Tod": "Swift Death",
  "Schnürender Reif": "Enlacing Loop",
  "Schockfinesse": "Shock Finesse",
  "Schockzunahmen – Entladung": "Shock Augments — Discharge",
  "Schockzunahmen – Woge": "Shock Augments — Surge",
  "Schreckenskolben": "Dread Mace",
  "Schreckensschild": "Dread Shield",
  "Schreckensschwengel": "Dread Poleaxe",
  "Schreisiegel": "Screamseal",
  "Schriftrolle der Amnesie": "Scroll of Amnesia",
  "Schriftrolle der Flucht": "Scroll of Escape",
  "Schutz": "Ward",
  "Schwarze Schiene": "Black Rail",
  "Schwarzholzkeule": "Blackwood Club",
  "Schwarzholz­keule": "Blackwood Club",
  "Schwebefluse": "Floaty Bobble",
  "Schädel und Stahl": "Skull and Steel",
  "Schädelknacker": "Skullcracker",
  "Schädelspalter": "Skullsplitter",
  "Seelenbeobachter­reif": "Soulwatch Hoop",
  "Seelenexplosion-Stab": "Soulburst Staff",
  "Seherstab": "Seer's Staff",
  "Serpentinenstab": "Serpentine Wand",
  "Sica": "Sica",
  "Signet der Nachtgeborenen": "Nightborne Signet",
  "Silberstern": "Silver Star",
  "Sippenfürst­band": "Kin-lord Band",
  "Sitz des Hasses": "Hatred's Seat",
  "Skelettierter Beschützer": "Skeletal Protector",
  "Skorpion": "Scorpion",
  "Spalthammer": "Crag Hammer",
  "Sparr": "Sparr",
  "Spezialistenevolution": "Specialist Evolution",
  "Spule": "Coil",
  "Spulenhals­reif": "Coilneck Loop",
  "Stab der Grinsenden Schamanin": "Crook of the Grinning Shaman",
  "Stachelflegel": "Spiked Flail",
  "Stachelschwert": "Barbed Sword",
  "Stangenwaffe des Teufels": "Devil's Polearm",
  "Staubstein": "Dust Stone",
  "Stechender Wind": "Piercing Wind",
  "Steinerne Sense": "Stone Scythe",
  "Stiefel": "Boots",
  "Stiefel des Unheilvollen Vorhabens": "Boots of Baleful Intent",
  "Stimme der Sterne": "Voice of the Stars",
  "Sturmfinesse": "Storm Finesse",
  "Sturmschild": "Stormshield",
  "Sturmzunahmen": "Storm Augments",
  "Stählerner Reif": "Unbending Choker",
  "Subo-Truhe": "Subo Cache",
  "Subo-Truhe der Vollendung": "Subo Masterworking Cache",
  "Syrus' Riesentasche": "Syrus's Heaping Bag",
  "Säbelzahnsichel": "Sawtooth Sickle",
  "Säbelzahn­sichel": "Sawtooth Sickle",
  "Säugerfluch-Bogen": "Mammalbane Bow",
  "Söldnerkopfschutz": "Mercenary Helm",
  "Südlandring": "Southland Loop",
  "Tausendfüßerfinesse": "Centipede Finesse",
  "Tausendfüßer­effizienz": "Centipede Efficiency",
  "Tausendfüßer­innovation": "Centipede Innovation",
  "Tausendfüßer­kreis": "Millipedian Circle",
  "Tausendfüßer­zunahmen": "Centipede Augments",
  "Teufelszahn-Zauberstab": "Devil Tooth Wand",
  "Todeskolben": "Death Mace",
  "Todesweite": "Death's Reach",
  "Topfhelm des Kriegsherrn": "Warlord Greathelm",
  "Torwächterschlüssel": "Gate Guardian Key",
  "Totemstab": "Totemic Staff",
  "Totenbeschwörer-Mauer": "Necromancer Wall",
  "Totenbeschwörer­bewegung": "Necromancer Motion",
  "Totenbeschwörer­effizienz": "Necromancer Efficiency",
  "Totenbeschwörer­kräftigung": "Necromancer Invigoration",
  "Tracht des Unheilvollen Vorhabens": "Vestment of Baleful Intent",
  "Traumfänger": "Dream Catcher",
  "Tribut des Leuchtens": "Tribute of Radiance",
  "Tribut des Leuchtens (Resolut)": "Tribute of Radiance (Resolute)",
  "Tribut von Andariel": "Tribute of Andariel",
  "Truhe der Geringen Übel": "Cache of the Lesser Evils",
  "Truhe der Habgier": "Cache of Avarice",
  "Truhe der Legenden": "Cache of Legends",
  "Truhe der Prüfungen": "Cache of Trials",
  "Truhe der Vergessenen Seele": "Forgotten Soul Cache",
  "Truhe der Vollendung": "Masterworking Cache",
  "Truhe der Würdigen": "Cache of Worthy",
  "Truhe der Zierde": "Cache of Ornaments",
  "Truhe der boshaften Herzen": "Malignant Heart Cache",
  "Truhe der destillierten Furcht": "Distilled Fear Cache",
  "Truhe des Abstrusen Siegels": "Abstruse Sigil Cache",
  "Truhe des Bewegungsaspekts": "Movement Aspect Cache",
  "Truhe des Champions": "Champion's Cache",
  "Truhe des Defensivaspekts": "Defensive Aspect Cache",
  "Truhe des Offensivaspekts": "Offensive Aspect Cache",
  "Truhe des Ressourcenaspekts": "Resource Aspect Cache",
  "Truhe des Scharfrichters": "Beheader's Cache",
  "Truhe des Schlächters": "Slayer's Cache",
  "Truhe des Sieges": "Cache of Victory",
  "Truhe des Unheilvollen Fragments": "Baleful Fragments Cache",
  "Truhe des Vielseitigkeitsaspekts": "Utility Aspect Cache",
  "Truhe des Windenden Schutzes": "Coiling Ward Cache",
  "Truhe des Zerstreuten Prismas": "Scattered Prism Cache",
  "Truhe des Zerstörers": "Destroyer's Cache",
  "Truhe des lebenden Stahls": "Living Steel Cache",
  "Truhe mit Exquisitem Blut": "Exquisite Blood Cache",
  "Truhe mit legendärem Ring – Amethyst": "Legendary Ring Cache - Amethyst",
  "Truhe mit legendärem Ring – Diamant": "Legendary Ring Cache - Diamond",
  "Truhe mit legendärem Ring – Rubin": "Legendary Ring Cache - Ruby",
  "Truhe mit legendärem Ring – Saphir": "Legendary Ring Cache - Sapphire",
  "Truhe mit legendärem Ring – Schädel": "Legendary Ring Cache - Skull",
  "Truhe mit legendärem Ring – Smaragd": "Legendary Ring Cache - Emerald",
  "Truhe mit legendärem Ring – Topas": "Legendary Ring Cache - Topaz",
  "Truhe mit legendären Runen ": "[PH] Cache with Legendary Runes ",
  "Truhe mit wiederverwerteten Materialien": "Salvage Material Cache",
  "Truhe: Dritte Reise": "Third Journey Cache",
  "Truhe: Siebte Reise": "Seventh Journey Cache",
  "Truhe: Vierte Reise": "Fourth Journey Cache",
  "Tränenschleier-Amulett": "Tearveil Amulet",
  "Tunika": "Tunic",
  "Täuschungseffizienz": "Subterfuge Efficiency",
  "Täuschungsexpertise": "Subterfuge Expertise",
  "Ultimative Effizienz – Barbar": "Ultimate Efficiency — Barbarian",
  "Ultimative Effizienz – Jäger": "Ultimate Efficiency — Rogue",
  "Ultimative Effizienz – Zauberer": "Ultimate Efficiency —  Sorcerer",
  "Ultimative Effizienz —  Druide": "Ultimate Efficiency —  Druid",
  "Unaussprechliche Waren": "Unspeakable Goods",
  "Unendliche Geschenke der Urahnen": "Unceasing Gifts from the Ancestors",
  "Unendliche Goblin-Tribute der Unterstadt von Kurast": "Goblin's Unceasing Kurast Undercity Tributes",
  "Unendliche Runentruhe des Goblins": "Goblin's Unceasing Rune Cache",
  "Unendliche legendäre Runentruhe der Urahnen": "Unceasing Ancestors' Legendary Runes Cache",
  "Unendliche legendäre Urahnen-Tribute der Unterstadt von Kurast": "Unceasing Ancestors' Legendary Kurast Undercity Tributes",
  "Unendliches Goblingeschenk": "Unceasing Goblin Gift",
  "Unentzifferbares Signet": "Indecipherable Signet",
  "Ungebrochene Kette": "Unbroken Chain",
  "Unglückszeuge": "Witness to Woe",
  "Unheilsbote ": "Doom Harbinger ",
  "Unheilvolles Fragment": "Baleful Fragment",
  "Untergang": "Oblivion",
  "Untergangskaskett": "Doom Casque",
  "Unterstadt-Almosen": "Undercity Alms",
  "Unvollendetes Band": "Inchoate Band",
  "Uralte Erinnerung": "Ancient Memory",
  "Uraltes Totem": "Ancient Effigy",
  "Urraubtier­schutz": "Ur-Predator Ward",
  "Urteilshammer": "Doom Hammer",
  "Urzeitfetisch": "Primordial Fetish",
  "Vajra": "Vajra",
  "Vampirische Signettruhe": "Vampiric Signet Cache",
  "Varyana-Truhe": "Varyana Cache",
  "Varyana-Truhe der Vollendung": "Varyana Masterworking Cache",
  "Vehemente Zunahmen": "Vehement Augments",
  "Vehemenzring": "Vehement Halo",
  "Verdammnisrüstung": "Doom Armor",
  "Verdammnistreter": "Doom Treads",
  "Verderbnis": "Corruption",
  "Verfallinnovation": "Decay Innovation",
  "Vergessene Seele": "Forgotten Soul",
  "Vergoldete Stangenwaffe": "Gilded Polearm",
  "Verlässliche Truhe der Eisenwölfe": "The Iron Wolves' Dependable Cache",
  "Verlässliches Trio der Eisenwölfe": "The Iron Wolves' Most Dependable",
  "Vermachte Amulettsammlung ": "Ancestral Collection of Amulets ",
  "Vermachte Beinschützersammlung ": "Ancestral Collection of Leg Guards ",
  "Vermachte Brustpanzersammlung ": "Ancestral Collection of Chestplates ",
  "Vermachte Chaossammlung ": "Ancestral Collection of Chaos ",
  "Vermachte Einhandwaffensammlung ": "Ancestral Collection of One-handed Weapons ",
  "Vermachte Kopfschutzsammlung ": "Ancestral Collection of Helms ",
  "Vermachte Panzerhandschuh­sammlung ": "Ancestral Collection of Gauntlets ",
  "Vermachte Ringsammlung ": "Ancestral Collection of Rings ",
  "Vermachte Stiefelsammlung ": "Ancestral Collection of Boots ",
  "Vermachte Waffentruhe der Triune": "Ancestral Triune Arms Cache",
  "Vermachte Waffentruhe des Zirkels": "Ancestral Coven Arms Cache",
  "Vermachte Zirkelkiste": "Ancestral Coven Crate",
  "Vermachte Zweihandwaffen­sammlung ": "Ancestral Collection of Two-Handed Weapons ",
  "Vermächtnis der Schande": "Legacy of Disgrace",
  "Vernarbtes Siegel": "Scarred Seal",
  "Verrottetes Abbild": "Rotted Effigy",
  "Verrücktes Gebräu": "Crazy Brew",
  "Verschlungener Dorn": "Intertwined Thorn",
  "Verwüster": "Ravager",
  "Verzerrter Schutz": "Marred Guard",
  "Verzierter Schädel": "Decorated Skull",
  "Vielfältiger Stock": "Manifold Cane",
  "Vielseitigkeitsaspekte": "Utility Aspects",
  "Vigos schützendes Amulett": "Vigo's Protecting Amulet",
  "Vollendung": "Masterworking",
  "Vulgäre Kette": "Vulgar Chain",
  "Waffe": "Weapon",
  "Waffe der Eisenwölfe": "Iron Wolves' Weapon",
  "Waffenbeherrschungs­effizienz": "Weapon Mastery Efficiency",
  "Waffeneinstimmung – Barbar": "Weapon Attunement — Barbarian",
  "Waffeneinstimmung – Totenbeschwörer": "Weapon Attunement — Necromancer",
  "Waffenkiste der Eisenwölfe": "Iron Wolves' Weapon Case",
  "Waffenzunahmen": "Weapon Augments",
  "Waldjuwelen-Helmbarte": "Forestgem Halberd",
  "Waldzunahmen": "Forest Augments",
  "Wehklage-Reif": "Lamentation Choker",
  "Weltknoten­ring": "Worldknot Ring",
  "Weltliche Beständigkeit": "Worldly Endurance",
  "Weltliche Finesse": "Worldly Finesse",
  "Weltliche Gunst": "Worldly Fortune",
  "Weltliche Stabilität": "Worldly Stability",
  "Wendigkeitseffizienz": "Agility Efficiency",
  "Werbärinnovation": "Werebear Innovation",
  "Werbärzunahmen": "Werebear Augments",
  "Werwolf-Finesse": "Werewolf Finesse",
  "Werwolfzunahmen": "Werewolf Augments",
  "Wiedergängerbogen": "Revenant Bow",
  "Wilder Wandel": "Wild Transformations",
  "Windender Schutz": "Coiling Ward",
  "Wirbelstab": "Spinal Wand",
  "Wolfsbiss": "Wolf's Bite",
  "Wurzelfaust": "Rootfist",
  "Wutentbrannter Drescher": "Furious Thresher",
  "Wärme des Beschützers": "Protectors' Warmth",
  "Wöchentliche Bonusbeute": "Weekly Bonus Spoils",
  "Ysevetes Klagelied": "Ysevete's Dirge",
  "Zauberbinder": "Spellbinder",
  "Zaubererbewegung": "Sorcerer Motion",
  "Zaubererinnovation": "Sorcerer Innovation",
  "Zaubererinnovation – Feurig": "Sorcerer Innovation — Fiery",
  "Zaubererkontrolle": "Sorcerer Control",
  "Zaubererstabilität": "Sorcerer Stability",
  "Zeichen der Ehre II": "Marks of Honor II",
  "Zelebrantentruhe": "Celebrant's Cache",
  "Zepter des Weltenwächters": "Realmwarden's Scepter",
  "Zerstreutes Prisma": "Scattered Prism",
  "Zeterkern": "Clamor Core",
  "Zirkel": "Hoop",
  "Zitadellen-Schatztasche": "Citadel Treasure Bag",
  "Zorneffizienz": "Wrath Efficiency",
  "Zufällige legendäre Rune": "Random Legendary Rune",
  "Zunahmen": "Augmentations",
  "Zunahmentruhe": "Augment Cache",
  "Zunahmen – Meucheln": "Cutthroat Augments",
  "Zunge der Schlange": "Serpent's Tongue",
  "Zurückerlangtes Medaillon der Eisenwölfe": "Reclaimed Medallion of the Iron Wolves",
  "Zwillingsklinge": "Twin-blade",
  "Zähne der Natur": "Nature's Teeth",
  "[PH] Bigger Rep Cache": "[PH] Bigger Rep Cache",
  "[PH] Coiling Ward Cache": "[PH] Coiling Ward Cache",
  "[PH] Fear Jewel": "[PH] Fear Jewel",
  "[PH] Hell Affix": "[PH] Hell Affix",
  "[PH] Movement Aspect Cache II": "[PH] Movement Aspect Cache II",
  "[PH] Offensive Aspect Cache II": "[PH] Offensive Aspect Cache II",
  "[PH] Resource Aspect Cache II": "[PH] Resource Aspect Cache II",
  "[PH] Utility Aspect Cache II": "[PH] Utility Aspect Cache II",
  "[PH]Scroll of Fast Growth": "[PH]Scroll of Fast Growth",
  "Ältesten-Aegis": "Elder Aegis",
  "Ältesten-Breitaxt": "Elder Broadaxe",
  "Ältesten-Geisterarmbrust": "Elder Spirit Crossbow",
  "Ältesten-Langdolch": "Elder Shiv",
  "Ältesten-Sandale": "Elder's Sandal",
  "Ältesten-Sense": "Elder Scythe",
  "Ältesten-Stangenwaffe": "Elder Polearm",
  "Ältesten-Streitkolben": "Elder Mace",
  "Ödlandinnovation": "Wasteland Innovation",
  "Ödlandzunahmen": "Wasteland Augments",
  "Öse des Todlings": "Deathling's Eyelet",
  "Übler Schwenker": "Vile Censer",
};

// ============================================================================
// LEGENDARY ASPECT TRANSLATIONS
// ============================================================================
const aspectTranslations = {
  "Abprallender Aspekt": "Rebounding Aspect",
  "Abschirmender Aspekt": "Warding Aspect",
  "Aphotischer Aspekt": "Aphotic Aspect",
  "Apostolischer Aspekt": "Apostle's Aspect",
  "Aspekt der Ablenkung": "Aspect of Deflection",
  "Aspekt der Ahnenechos": "Aspect of Ancestral Echoes",
  "Aspekt der Ahnenmacht": "Aspect of Ancestral Force",
  "Aspekt der Anpassungsfähigkeit": "Aspect of Adaptability",
  "Aspekt der Assistenz": "Aspect of Assistance",
  "Aspekt der Auserwählten Rathmas": "Aspect of Rathma's Chosen",
  "Aspekt der Auszeichnung": "Aspect of Excellence",
  "Aspekt der Bekehrung": "Aspect of Proselytizing",
  "Aspekt der Berserkerwut": "Aspect of Berserk Fury",
  "Aspekt der Besinnung": "Aspect of Contemplation",
  "Aspekt der Beständigkeit": "Aspect of Endurance",
  "Aspekt der Blutarmut": "Aspect of Anemia",
  "Aspekt der Blutstacheln": "Aspect of Gore Quills",
  "Aspekt der Bodenstärke": "Aspect of Soil Power",
  "Aspekt der Brennenden Wut": "Aspect of Burning Rage",
  "Aspekt der Ebenenstärke": "Aspect of Plains Power",
  "Aspekt der Effizienz": "Aspect of Efficiency",
  "Aspekt der Eile": "Aspect of Quickening Fog",
  "Aspekt der Eisschritte": "Aspect of Frosty Strides",
  "Aspekt der Elementarschärfe": "Aspect of Elemental Acuity",
  "Aspekt der Energiefülle": "Aspect of Abundant Energy",
  "Aspekt der Erdbeben": "Aspect of Earthquakes",
  "Aspekt der Erlösung": "Aspect of Salvation",
  "Aspekt der Erwartungsvollen": "Aspect of the Expectant",
  "Aspekt der Festung": "Aspect of the Fortress",
  "Aspekt der Fluidität": "Aspect of Fluidity",
  "Aspekt der Flüchtigen Bedrohung": "Aspect of Elusive Menace",
  "Aspekt der Giftwolken": "Aspect of Poisonous Clouds",
  "Aspekt der Goldenen Stunde": "Aspect of the Golden Hour",
  "Aspekt der Grenzenlosen Wut": "Aspect of Limitless Rage",
  "Aspekt der Gunst": "Aspect of Fortune",
  "Aspekt der Hartnäckigkeit": "Aspect of Tenacity",
  "Aspekt der Hast": "Aspect of Haste",
  "Aspekt der Herrschaft": "Aspect of Dominance",
  "Aspekt der Himmelsstärke": "Aspect of Sky Power",
  "Aspekt der Hingabe": "Aspect of Dedication",
  "Aspekt der Inbrunst Jacques'": "Aspect of Jacques' Fervor",
  "Aspekt der Kontrolle": "Aspect of Control",
  "Aspekt der Konzentration": "Aspect of Concentration",
  "Aspekt der Kühnheit": "Aspect of Audacity",
  "Aspekt der Leere": "Aspect of the Void",
  "Aspekt der Lichtlinderung": "Aspect of the Light's Mending",
  "Aspekt der Loyalität": "Aspect of Loyalty",
  "Aspekt der Macht": "Aspect of Might",
  "Aspekt der Metamorphose": "Aspect of Metamorphosis",
  "Aspekt der Militanz": "Aspect of Militance",
  "Aspekt der Naturgewalt": "Aspect of Nature's Savagery",
  "Aspekt der Nordwache": "Aspect of the Northern Guard",
  "Aspekt der Pestilenz": "Aspect of Pestilence",
  "Aspekt der Pilgerreise": "Aspect of Pilgrim's Progress",
  "Aspekt der Qual": "Aspect of Torment",
  "Aspekt der Rachsucht": "Aspect of Retaliation",
  "Aspekt der Reanimation": "Aspect of Reanimation",
  "Aspekt der Rechtsprechung Tyraels": "Aspect of Tyrael's Jurisdiction",
  "Aspekt der Riesenschritte": "Aspect of Giant Strides",
  "Aspekt der Salbung Hales": "Aspect of Hale's Salve",
  "Aspekt der Schnelligkeit": "Aspect of Alacrity",
  "Aspekt der Schuld des Wechselbalgs": "Aspect of the Changeling's Debt",
  "Aspekt der Seuchenspitzen": "Aspect of Pestilent Points",
  "Aspekt der Souveränität Lageras": "Aspect of Lagera's Sovereignty",
  "Aspekt der Stampede": "Aspect of the Stampede",
  "Aspekt der Sternensplitter": "Aspect of Star Shards",
  "Aspekt der Synergie": "Aspect of Synergy",
  "Aspekt der Turbulenz": "Aspect of Turbulence",
  "Aspekt der Unbeugsamen": "Aspect of the Indomitable",
  "Aspekt der Unersättlichen": "Aspect of the Unsatiated",
  "Aspekt der Untersagung": "Aspect of Interdiction",
  "Aspekt der Verdammten": "Aspect of the Damned",
  "Aspekt der Verderbnis": "Aspect of Corruption",
  "Aspekt der Vergeltung": "Aspect of Retribution",
  "Aspekt der Vermeidung": "Aspect of Avoidance",
  "Aspekt der Verseuchung": "Aspect of Contamination",
  "Aspekt der Verzahnung": "Aspect of Serration",
  "Aspekt der Vielseitigkeit": "Versatility Aspect",
  "Aspekt der Vorwärtsbewegung": "Aspect of Forward Momentum",
  "Aspekt der Waldstärke": "Aspect of Forest Power",
  "Aspekt der Wutkontrolle": "Aspect of Anger Management",
  "Aspekt der Zyklonmacht": "Aspect of Cyclonic Force",
  "Aspekt der Züchtigung": "Aspect of Retribution",
  "Aspekt der abgeschöpften Verpflegung": "Aspect of Siphoned Victuals",
  "Aspekt der ablenkenden Barriere": "Aspect of the Deflecting Barrier",
  "Aspekt der abzweigenden Salven": "Aspect of Branching Volleys",
  "Aspekt der antiklinalen Explosion": "Aspect of Anticline Burst",
  "Aspekt der ausgesprochenen Ermächtigung": "Aspect of Vocalized Empowerment",
  "Aspekt der beißenden Kälte": "Aspect of Biting Cold",
  "Aspekt der berstenden Gifte": "Aspect of Bursting Venoms",
  "Aspekt der berstenden Knochen": "Aspect of Bursting Bones",
  "Aspekt der bindenden Glut": "Aspect of Binding Embers",
  "Aspekt der bitteren Infektion": "Aspect of Bitter Infection",
  "Aspekt der brennenden Tobsucht": "Aspect of the Flaming Rampage",
  "Aspekt der destillierten Anima": "Aspect of Distilled Anima",
  "Aspekt der dornigen Rache": "Aspect of Bristling Vengeance",
  "Aspekt der durchdringenden Statik": "Aspect of Piercing Static",
  "Aspekt der einbrechenden Dunkelheit": "Aspect of Plunging Darkness",
  "Aspekt der einfachen Vergeltung": "Aspect of Simple Reprisal",
  "Aspekt der eisigen Wache": "Aspect of the Frozen Guard",
  "Aspekt der elektrischen Klauen": "Aspect of Electrified Claws",
  "Aspekt der elementalen Konstellation": "Aspect of Elemental Constellation",
  "Aspekt der elementaren Konstellation": "Aspect of Elemental Constellation",
  "Aspekt der endlosen Klauen": "Aspect of Endless Talons",
  "Aspekt der engelsgleichen Vollendung": "Aspect of Angelic Masterwork",
  "Aspekt der erschütternden Schläge": "Aspect of Concussive Strikes",
  "Aspekt der fallenden Federn": "Aspect of Falling Feathers",
  "Aspekt der fesselnden Furcht": "Aspect of Apprehension",
  "Aspekt der feurigen Spalten": "Aspect of Incendiary Fissures",
  "Aspekt der flinken Flügel": "Aspect of Fleet Wings",
  "Aspekt der flüchtigen Schatten": "Aspect of Volatile Shadows",
  "Aspekt der gebrochenen Verteidigung": "Aspect of Shattered Defenses",
  "Aspekt der gefrorenen Erinnerungen": "Aspect of Frozen Memories",
  "Aspekt der gefrorenen Tundra": "Aspect of the Frozen Tundra",
  "Aspekt der gehärteten Knochen": "Aspect of Hardened Bones",
  "Aspekt der grausamen Versorgung": "Aspect of Cruel Sustenance",
  "Aspekt der greifenden Adern": "Aspect of Grasping Veins",
  "Aspekt der grünen Wiederherstellung": "Aspect of Verdant Restoration",
  "Aspekt der heiklen Wendigkeit": "Aspect of Tenuous Agility",
  "Aspekt der heiligen Bestrafung": "Aspect of Holy Punishment",
  "Aspekt der heiligen Kadenz": "Aspect of Holy Cadence",
  "Aspekt der heimkehrenden Federn": "Aspect of Recalling Feathers",
  "Aspekt der heimlichen Schritte": "Aspect of Sly Steps",
  "Aspekt der hereinbrechenden Flut": "Aspect of Impending Deluge",
  "Aspekt der himmlischen Stärke": "Aspect of Heavenly Strength",
  "Aspekt der härtenden Schläge": "Aspect of Tempering Blows",
  "Aspekt der imitierten Infusion": "Aspect of Imitated Imbuement",
  "Aspekt der inneren Ruhe": "Aspect of Inner Calm",
  "Aspekt der instabilen Infusionen": "Aspect of Unstable Imbuements",
  "Aspekt der kinetischen Unterdrückung": "Aspect of Kinetic Suppression",
  "Aspekt der kombinierten Schläge": "Aspect of Combined Strikes",
  "Aspekt der kunstvollen Initiative": "Aspect of Artful Initiative",
  "Aspekt der nebulösen Gebräue": "Aspect of Nebulous Brews",
  "Aspekt der okkulten Herrschaft": "Aspect of Occult Dominion",
  "Aspekt der peitschenden Winde": "Aspect of Fierce Winds",
  "Aspekt der rauschenden Wildnis": "Aspect of the Rushing Wilds",
  "Aspekt der reaktiven Rüstung": "Aspect of Reactive Armor",
  "Aspekt der sanften Brise": "Aspect of the Calm Breeze",
  "Aspekt der schneidenden Kälte": "Aspect of Piercing Cold",
  "Aspekt der teuflischen Völlerei": "Aspect of Fel Gluttony",
  "Aspekt der tobenden Werbestie": "Aspect of the Rampaging Werebeast",
  "Aspekt der tollwütigen Bestie": "Aspect of the Rampaging Werebeast",
  "Aspekt der tödlichen Dämmerung": "Aspect of Lethal Dusk",
  "Aspekt der umgelenkten Macht": "Aspect of Redirected Force",
  "Aspekt der umkreisenden Klingen": "Aspect of Encircling Blades",
  "Aspekt der unaufhaltsamen Macht": "Aspect of Unstoppable Force",
  "Aspekt der unersättlichen Rage": "Aspect of Voracious Rage",
  "Aspekt der ungebrochenen Kette": "Aspect of the Unbroken Tether",
  "Aspekt der unheiligen Fesseln": "Aspect of the Unholy Tether",
  "Aspekt der unnachgiebigen Treffer": "Aspect of Unyielding Hits",
  "Aspekt der uralten Flamme": "Aspect of Ancient Flame",
  "Aspekt der verfluchten Aura": "Aspect of the Cursed Aura",
  "Aspekt der verfluchten Berührung": "Aspect of Accursed Touch",
  "Aspekt der verschwommenen Bestie": "Aspect of the Blurred Beast",
  "Aspekt der versengten Extremitäten": "Aspect of Singed Extremities",
  "Aspekt der verstärkten Federn": "Aspect of Empowered Feathers",
  "Aspekt der verzehrenden Flammen": "Aspect of Engulfing Flames",
  "Aspekt der vielschichtigen Schutze": "Aspect of Layered Wards",
  "Aspekt der wahren Sicht": "Aspect of True Sight",
  "Aspekt der wiederhergestellten Essenzen": "Aspect of Restored Essence",
  "Aspekt der wilden Klauen": "Aspect of Wild Claws",
  "Aspekt der zeitweiligen Schnitte": "Aspect of Temporal Incisions",
  "Aspekt der zerborstenen Sterne": "Aspect of Shattered Stars",
  "Aspekt der zerfetzenden Klingen": "Aspect of Shredding Blades",
  "Aspekt der zersplitternden Energie": "Aspect of Splintering Energy",
  "Aspekt der zersplitternden Scherben": "Aspect of Splintering Shards",
  "Aspekt der zerstörerischen Explosion": "Aspect of Overwhelming Currents",
  "Aspekt der zertrampelten Erde": "Aspect of the Trampled Earth",
  "Aspekt der zügigen Verbindung": "Aspect of Quickening Pulse",
  "Aspekt der Überhitzung": "Aspect of Overheating",
  "Aspekt der Überraschung": "Aspect of Surprise",
  "Aspekt der überwältigenden Strömung": "Aspect of Overwhelming Currents",
  "Aspekt des Abschlachtens": "Aspect of Slaughter",
  "Aspekt des Ahnensturms": "Aspect of Ancestral Charge",
  "Aspekt des Alphas": "Aspect of the Alpha",
  "Aspekt des Armageddon": "Aspect of Armageddon",
  "Aspekt des Aufstiegs": "Aspect of Ascension",
  "Aspekt des Befalls": "Aspect of Infestation",
  "Aspekt des Beschützers": "Aspect of the Protector",
  "Aspekt des Bärenschreckens": "Aspect of the Ursine Horror",
  "Aspekt des Dienstes und der Opfer": "Aspect of Service and Sacrifice",
  "Aspekt des Einbalsamierens": "Aspect of the Embalmer",
  "Aspekt des Eisernen Regens": "Aspect of Iron Rain",
  "Aspekt des Exorzismus ": "Aspect of Exorcism ",
  "Aspekt des Explosiven Nebels": "Aspect of Explosive Mist",
  "Aspekt des Fanatikerbundes": "Aspect of the Zealot's Covenant",
  "Aspekt des Feuervogels": "Aspect of the Firebird",
  "Aspekt des Funkenschlags": "Aspect of Conflagration",
  "Aspekt des Gebieterzephyrs": "Aspect of the Arbiter's Zephyr",
  "Aspekt des Gefrorenen Sogs": "Aspect of the Frozen Wake",
  "Aspekt des Giftigen Eises": "Aspect of Noxious Ice",
  "Aspekt des Heldenmuts": "Aspect of Valiance",
  "Aspekt des Hochgefühls": "Aspect of Exhilaration",
  "Aspekt des Jüngers": "Aspect of the Disciple",
  "Aspekt des Molochbundes": "Aspect of the Juggernaut's Covenant",
  "Aspekt des Moments": "Aspect of Momentum",
  "Aspekt des Mondaufgangs": "Aspect of the Moonrise",
  "Aspekt des Nachbebens": "Aspect of The Aftershock",
  "Aspekt des Pfeilsturms": "Aspect of Arrow Storms",
  "Aspekt des Richters": "Aspect of the Judicator",
  "Aspekt des Schattens": "Aspect of the Umbral",
  "Aspekt des Treibsands": "Aspect of Quicksand",
  "Aspekt des Ultimativen Schattens": "Aspect of Ultimate Shadow",
  "Aspekt des Unerschütterlichen": "Aspect of the Unwavering",
  "Aspekt des Ungehorsams": "Aspect of Disobedience",
  "Aspekt des Valintyr": "Aspect of the Valintyr",
  "Aspekt des Verfalls": "Aspect of Decay",
  "Aspekt des Wildzorns": "Aspect of the Wildrage",
  "Aspekt des Wolfssturms": "Aspect of Wolf's Rain",
  "Aspekt des agilen Wolfs": "Aspect of the Agile Wolf",
  "Aspekt des aufgeladenen Blitzes": "Aspect of Charged Flash",
  "Aspekt des aufgeschobenen Aussterbens": "Aspect of Delayed Extinction",
  "Aspekt des berserkerhaften Zerreißens": "Aspect of Berserk Ripping",
  "Aspekt des berstenden Stahls": "Aspect of Shattering Steel",
  "Aspekt des besonnenen Herzens": "Aspect of the Prudent Heart",
  "Aspekt des beständigen Stampfens": "Aspect of Perpetual Stomping",
  "Aspekt des betäubenden Zorns": "Aspect of Numbing Wrath",
  "Aspekt des bindenden Morasts": "Aspect of Binding Morass",
  "Aspekt des dunklen Heulens": "Aspect of the Dark Howl",
  "Aspekt des dunklen Tanzes": "Aspect of the Dark Dance",
  "Aspekt des einnehmenden Zorns": "Aspect of Encroaching Wrath",
  "Aspekt des eisernen Kriegers": "Aspect of the Iron Warrior",
  "Aspekt des elementaren Schicksals": "Aspect of Elemental Fate",
  "Aspekt des engelsgleichen Vollendung": "Aspect of Angelic Masterwork",
  "Aspekt des entblößten Fleisches": "Aspect of Exposed Flesh",
  "Aspekt des erweckten Geistes": "Aspect of Mind's Awakening",
  "Aspekt des explosiven Schwungs": "Aspect of Explosive Verve",
  "Aspekt des fieberhaften Anfallens": "Aspect of Fevered Mauling",
  "Aspekt des flinken Geists": "Aspect of Swift Spirit",
  "Aspekt des frühzeitigen Todes": "Aspect of Untimely Death",
  "Aspekt des gebrochenen Bodens": "Aspect of Sundered Ground",
  "Aspekt des gefrorenen Erwachens": "Aspect of the Frozen Wake",
  "Aspekt des gefrorenen Orbits": "Aspect of Frozen Orbit",
  "Aspekt des geraubten Elans": "Aspect of Stolen Vigor",
  "Aspekt des geteilten Leids": "Aspect of Shared Misery",
  "Aspekt des gipfelnden Furors": "Aspect of Apogeic Furor",
  "Aspekt des gleißenden Lichts": "Aspect of Dazzling Light",
  "Aspekt des großen Festmahls": "Aspect of the Great Feast",
  "Aspekt des heiklen Überlebens": "Aspect of Tenuous Survival",
  "Aspekt des herkulischen Spektakels": "Aspect of Herculean Spectacle",
  "Aspekt des himmlischen Zwists": "Aspect of Celestial Strife",
  "Aspekt des hungernden Blutes": "Aspect of Hungry Blood",
  "Aspekt des höchsten Ruhms": "Aspect of Utmost Glory",
  "Aspekt des irdenen Schutzes": "Aspect of the Protector",
  "Aspekt des kriechenden Kadavers": "Aspect of Creeping Cadaver",
  "Aspekt des kräftigenden Willens": "Aspect of Invigorating Will",
  "Aspekt des langen Schattens": "Aspect of the Long Shadow",
  "Aspekt des lindernden Steins": "Aspect of Mending Stone",
  "Aspekt des metamorphen Steins": "Aspect of Metamorphic Stone",
  "Aspekt des mächtigen Blutes": "Aspect of Potent Blood",
  "Aspekt des natürlichen Gleichgewichts": "Aspect of Natural Balance",
  "Aspekt des orangefarbenen Herolds": "Aspect of the Orange Herald",
  "Aspekt des packenden Wirbelwinds": "Aspect of Grasping Whirlwind",
  "Aspekt des potenten Austauschs": "Aspect of Potent Exchange",
  "Aspekt des rasenden Todes": "Aspect of Frenzied Dead",
  "Aspekt des sammelnden Konters": "Aspect of Rallying Reversal",
  "Aspekt des schleichenden Todes": "Aspect of Creeping Death",
  "Aspekt des schrecklichen Wirbelwinds": "Aspect of the Dire Whirlwind",
  "Aspekt des schützenden Sturms": "Aspect of Shielding Storm",
  "Aspekt des sengenden Schutzes": "Aspect of Searing Wards",
  "Aspekt des stimulierenden Nebels": "Aspect of Quickening Fog",
  "Aspekt des strikten Erlasses": "Aspect of Firm Decree",
  "Aspekt des stärkenden Seelenernters": "Aspect of Empowering Reaper",
  "Aspekt des umringten Weisen": "Aspect of the Crowded Sage",
  "Aspekt des unausweichlichen Schicksals": "Aspect of Inevitable Fate",
  "Aspekt des unerbittlichen Waffenmeisters": "Aspect of the Relentless Armsmaster",
  "Aspekt des unheimlichen Verrats": "Aspect of Uncanny Treachery",
  "Aspekt des verfallenden Humerus": "Aspect of Decaying Humerus",
  "Aspekt des wütenden Sturms": "Aspect of the Tempest",
  "Aspekt von Akarats Segen": "Aspect of Akarat's Blessing",
  "Aspekt von Bul-Kathos": "Aspect of Bul-Kathos",
  "Aspekt von Glynns Amboss": "Aspect of Glynn's Anvil",
  "Aspekt von Lapas Schriften": "Aspect of Lapa's Scripture",
  "Aspekt von Watkins Gesetz": "Aspect of Watkins' Law",
  "Assimilierender Aspekt": "Assimilation Aspect",
  "Aufladender Aspekt": "Recharging Aspect",
  "Ausbalancierter Aspekt": "Balanced Aspect",
  "Ausbeutender Aspekt": "Exploiter's Aspect",
  "Ballistischer Aspekt": "Ballistic Aspect",
  "Bedrohlicher Aspekt": "Menacing Aspect",
  "Beschleunigender Aspekt": "Accelerating Aspect",
  "Bestattender Aspekt": "Requiem Aspect",
  "Betrügender Aspekt": "Cheat's Aspect",
  "Blitzbogens Aspekt": "Lightning Rod Aspect",
  "Blitztänzelnder Aspekt": "Lightning Dancer's Aspect",
  "Blutberserkers Aspekt": "Relentless Berserker's Aspect",
  "Blutfresser-Aspekt": "Bloodfeeder Aspect",
  "Blutgebadeter Aspekt": "Blood-bathed Aspect",
  "Blutgeborener Aspekt": "Lord of Blood's Aspect",
  "Blutgetränkter Aspekt": "Blood-soaked Aspect",
  "Blutholender Aspekt": "Blood Getter's Aspect",
  "Blutsuchender Aspekt": "Blood Seeker's Aspect",
  "Blutwogender Aspekt": "Tidal Aspect",
  "Bolzenschießender Aspekt": "Mired Sharpshooter's  Aspect",
  "Brandschatzender Aspekt": "Raider's Aspect",
  "Brandstiftender Aspekt": "Firestarter Aspect",
  "Brechender Aspekt": "Wanton Rupture Aspect",
  "Bärenklan-Berserkers Aspekt": "Bear Clan Berserker's Aspect",
  "Des Kampfmagiers Aspekt": "Battle Caster's Aspect",
  "Des Totengenerals Aspekt": "Unyielding Commander's Aspect",
  "Dienender Aspekt": "Squire's Aspect",
  "Dornliebender Aspekt": "Sticker-thought Aspect",
  "Duellierender Aspekt": "Duelist's Aspect",
  "Eindringender Aspekt": "Infiltrator's Aspect",
  "Eisalchemischer Aspekt": "Icy Alchemist's Aspect",
  "Eisenblütiger Aspekt": "Iron Blood Aspect",
  "Eiserner Aspekt": "Aspect of Might",
  "Eisgriffs Aspekt": "Coldclip Aspect",
  "Eitler Aspekt": "Conceited Aspect",
  "Elementarer Aspekt": "Elementalist's Aspect",
  "Elementaristen-Aspekt": "Elementalist's Aspect",
  "Energiespendender Aspekt": "Energizing Aspect",
  "Entfesselnder Aspekt": "Escape Artist's Aspect",
  "Entwischender Aspekt": "Eluding Aspect",
  "Entzweireißender Aspekt": "Rip and Tear Aspect",
  "Erdschützender Aspekt": "Earthguard Aspect",
  "Erdwüters Aspekt": "Earthstriker's Aspect",
  "Erfahrener Aspekt": "Veteran Brawler's Aspect",
  "Erschütternder Aspekt": "Jolting Aspect",
  "Essenz-Aspekt": "Aspect of the Umbral",
  "Ewiglebender Aspekt": "Everliving Aspect",
  "Ewigschnitters Aspekt": "Inexorable Reaper's Aspect",
  "Feiger Aspekt": "Craven Aspect",
  "Flammenwandlers Aspekt": "Flamewalker's Aspect",
  "Flammenwerfers Aspekt": "Flamethrower's Aspect",
  "Frostbeißender Aspekt": "Frostbitten Aspect",
  "Frostblitzender Aspekt": "Frostblitz Aspect",
  "Frostbrand-Aspekt": "Frostblitz Aspect",
  "Galvanoschlitzers Aspekt": "Galvanized Slasher's  Aspect",
  "Gefräßiger Aspekt": "Ravenous Aspect",
  "Geist-Aspekt": "Aspect of the Changeling's Debt",
  "Geistgefangener Aspekt": "Imprisoned Spirit's Aspect",
  "Geistverbundener Aspekt": "Spirit Bond Aspect",
  "Geistwandelnder Aspekt": "Ghostwalker Aspect",
  "Geladener Aspekt": "Charged Aspect",
  "Gestaltwandelnder Aspekt": "Skinwalker's Aspect",
  "Giftalchemischer Aspekt": "Toxic Alchemist's Aspect",
  "Glückbringender Aspekt": "Luckbringer Aspect",
  "Grauenwahrsagers Aspekt": "Fell Soothsayer's Aspect",
  "Gravitativer Aspekt": "Gravitational Aspect",
  "Groll-Aspekt": "Aspect of Ancestral Echoes",
  "Halsbrecherischer Aspekt": "Breakneck Bandit's Aspect",
  "Heißlodernder Aspekt": "Flash Fire Aspect",
  "Hektischer Aspekt": "Hectic Aspect",
  "Hitzblütiger Aspekt": "Blood Boiling Aspect",
  "Hochgeschwindigkeit Aspekt": "High Velocity Aspect",
  "Hochgeschwindigkeits-Aspekt": "High Velocity Aspect",
  "Hungerleidender Aspekt": "Starving Ravager's  Aspect",
  "Hünenhafter Aspekt": "Hulking Aspect",
  "Kampfwütiger Aspekt": "Battle-Mad Aspect",
  "Keilender Aspekt": "Vehement Brawler's Aspect",
  "Klingenmeisters Aspekt": "Edgemaster's Aspect",
  "Klingentanzender Aspekt": "Bladedancer's Aspect",
  "Knochenstürmender Aspekt": "Osseous Gale Aspect",
  "Knochenzerstäubender Aspekt": "Bone Duster's Aspect",
  "Kontroll-Aspekt": "Aspect of Control",
  "Kratzbürstiger Aspekt": "Bristleback Aspect",
  "Kältebringender Aspekt": "Coldbringer's Aspect",
  "Lebhafter Aspekt": "Vigorous Aspect",
  "Leichenhafter Aspekt": "Cadaverous Aspect",
  "Lotuserntender Aspekt": "Reaping Lotus' Aspect",
  "Löschender Aspekt": "Slaking Aspect",
  "Magierfürstlicher Aspekt": "Mage-Lord's Aspect",
  "Molochs Aspekt": "Juggernaut's Aspect",
  "Mondzorn Aspekt": "Moonrage Aspect",
  "Mächtiger Aspekt": "Raw Might Aspect",
  "Nachtheulers Aspekt": "Nighthowler's Aspect",
  "Nadelfeuriger Aspekt": "Needleflare Aspect",
  "Offenbarender Aspekt": "Revelator's Aspect",
  "Opfernder Aspekt": "Sacrificial Aspect",
  "Opportuner Aspekt": "Opportunist's Aspect",
  "Peinigender Aspekt": "Torturous Aspect",
  "Phasenpoltergeists Aspekt": "Phasing Poltergeist's Aspect",
  "Prellender Aspekt": "Bruiser's Aspect",
  "Quälers Aspekt": "Tormentor's Aspect",
  "Rache-Aspekt": "Aspect of Retribution",
  "Rachjäger-Aspekt": "Vengeful Aspect",
  "Rachsüchtiger Aspekt": "Vengeful Aspect",
  "Rauffreudiger Aspekt": "Brawler's Aspect",
  "Reumütiger Aspekt": "The Penitent's Aspect",
  "Runenbindender Aspekt": "Runeworker's Conduit Aspect",
  "Scharfrichters Aspekt": "Executioner's Aspect",
  "Schattennebels Aspekt": "Shademist Aspect",
  "Schattenschnitters Aspekt": "Shadowslicer Aspect",
  "Schattiger Aspekt": "Umbrous Aspect",
  "Schaudernder Aspekt": "Shivering Aspect",
  "Schlachthäuptlings Aspekt": "TODO",
  "Schlachthäuptlings-Aspekt": "Bold Chieftain's Aspect",
  "Schmetternder Aspekt": "Smiting Aspect",
  "Schneeverschleierter Aspekt": "Snowveiled Aspect",
  "Schneewachender Aspekt": "Snowguard's Aspect",
  "Schnellblütiger Aspekt": "Fastblood Aspect",
  "Schneller Aspekt": "Rapid Aspect",
  "Schockgefrorener Aspekt": "Snap Frozen Aspect",
  "Schädelbrechender Aspekt": "Skullbreaker's Aspect",
  "Schäfers Aspekt": "Shepherd's Aspect",
  "Schützender Aspekt": "Protecting Aspect",
  "Seelenerntender Aspekt": "Reaper's Aspect",
  "Seelenzerschmetternder Aspekt": "Shattered Spirit's Aspect",
  "Seismischer Aspekt": "Seismic-shift Aspect",
  "Skrupelloser Aspekt": "Ruthless Aspect",
  "Splitternder Aspekt": "Splintering Aspect",
  "Sprengfallenstellender Aspekt": "Blast-Trapper's Aspect",
  "Stabiler Aspekt": "Stable Aspect",
  "Stahlberserkers Aspekt": "Steadfast Berserker's Aspect",
  "Staubteufels Aspekt": "Dust Devil's Aspect",
  "Steinbrüchiger Aspekt": "Crashstone Aspect",
  "Sternenbeschienener Aspekt": "Starlight Aspect",
  "Sturmgewaltiger Aspekt": "Mighty Storm's Aspect",
  "Sturmjagender Aspekt": "Stormchaser's Aspect",
  "Sturmklaues Aspekt": "Stormclaw's Aspect",
  "Sturmkrähes Aspekt": "Stormcrow's Aspect",
  "Sturmschwellender Aspekt": "Stormswell Aspect",
  "Sturmschwel­lender Aspekt": "Storm Swell Aspect",
  "Sturmwandelnder Aspekt": "Stormshifter's Aspect",
  "Symbiotischer Aspekt": "Symbiotic Aspect",
  "Teuflischer Aspekt": "Devilish Aspect",
  "Todessehnsüchtiger Aspekt": "Death Wish Aspect",
  "Trickreicher Aspekt": "Trickshot Aspect",
  "Trutziger Aspekt": "Bulwark's Aspect",
  "Tugendhafter Aspekt": "Virtuous Aspect",
  "Täuschender Aspekt": "Trickster's Aspect",
  "Tödliche Flinkheit": "Aspect of Lethal Dexterity",
  "Umhüllter Aspekt": "Encased Aspect",
  "Unersättlicher Aspekt": "Insatiable Aspect",
  "Unnachgiebiger Aspekt": "Unrelenting Aspect",
  "Unterirdischer Aspekt": "Subterranean Aspect",
  "Unvergänglicher Aspekt": "Aspect of Unyielding Hits",
  "Verborgener Aspekt": "Clandestine Aspect",
  "Vergletscherter Aspekt": "Glacial Aspect",
  "Verhüllender Aspekt": "Enshrouding Aspect",
  "Verjüngender Aspekt": "Rejuvenating Aspect",
  "Verpesteter Aspekt": "Blighted Aspect",
  "Verrottender Aspekt": "Rotting Aspect",
  "Verschlagener Aspekt": "Aspect of the Blur",
  "Verstümmelter Aspekt": "Mangled Aspect",
  "Verwüstender Aspekt": "Ravager's Aspect",
  "Virulenter Aspekt": "Virulent Aspect",
  "Vorderster Aspekt": "Vanguard's Aspect",
  "Waffenmeisters Aspekt": "Weapon Master's Aspect",
  "Widerständiger Aspekt": "Resistant Assailant's Aspect",
  "Wiederholender Aspekt": "Repeating Aspect",
  "Wildblitzender Aspekt": "Wildbolt Aspect",
  "Windpeitschender Aspekt": "Windlasher Aspect",
  "Windwütender Aspekt": "Wind Striker Aspect",
  "Winterhands Aspekt": "Winter Touch Aspect",
  "Wunderkinds Aspekt": "Prodigy's Aspect",
  "Wölfischer Aspekt": "Dire Wolf's Aspect",
  "Zerfleischender Aspekt": "Flesh-Rending Aspect",
  "Zerfleischers Aspekt": "Mangler's Aspect",
  "Zermalmer-Aspekt": "Aspect of the Crushing Earth",
  "Zerschmetterter Aspekt": "Shattered Aspect",
  "Zerstückelnder Aspekt": "Slice and Dice Aspect",
  "Zündelnder Aspekt": "Incendiary Aspect",
  "Züngelnder Aspekt": "Serpentine Aspect",
  "Überladener Aspekt": "Overcharged Aspect",
  "Überrollender Aspekt": "Shockwave Aspect",
};

// ============================================================================
// TEMPERING RECIPE TRANSLATIONS
// ============================================================================
const temperingTranslations = {
  "Barbarenbewegung": "Barbarian Movement",
  "Druidenbewegung": "Druid Movement",
  "Feuerfinesse": "Fire Finesse",
  "Feuerzunahmen: Woge": "Fire Augments: Surge",
  "Frostfinesse": "Frost Finesse",
  "Frostzunahmen: Woge": "Frost Augments: Surge",
  "Geistgeborenen-Bewegung": "Spiritborn Movement",
  "Physische Finesse": "Physical Finesse",
  "Schattenfinesse": "Shadow Finesse",
  "Schattenzunahmen: Woge": "Shadow Augments: Surge",
  "Schockfinesse": "Shock Finesse",
  "Schockzunahmen: Woge": "Augments: Surge",
  "Schurkenbewegung": "Rogue Movement",
  "Totenbeschwörerbewegung": "Necromancer Movement",
  "Toxinfinesse": "Toxin Finesse",
  "Toxinzunahmen: Woge": "Toxin Augments: Surge",
  "Weltliche Beständigkeit": "Worldly Endurance",
  "Weltliche Stabilität": "Worldly Stability",
  "Zaubererbewegung": "Sorcerer Movement",
  "Übernatürliche Beständigkeit": "Supernatural Endurance",
  "Übernatürliche Stabilität": "Supernatural Stability",
};

// Combine all translations for pattern matching
const allTranslations = {
  ...glyphTranslations,
  ...itemTranslations,
  ...aspectTranslations,
  ...temperingTranslations
};

// Sort by length (longest first) to avoid partial replacements
const sortedKeys = Object.keys(allTranslations).sort((a, b) => b.length - a.length);

// Build regex pattern for all German terms
const pattern = new RegExp(
  '\\b(' + sortedKeys.map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')\\b',
  'g'
);

// Track processed nodes to avoid double-processing
const processedNodes = new WeakSet();

function translateTextNode(textNode) {
  if (processedNodes.has(textNode)) return;

  const originalText = textNode.textContent;
  let newText = originalText;

  // Replace each German term with "German (English)" format
  newText = newText.replace(pattern, (match) => {
    const english = allTranslations[match];
    if (english && !originalText.includes(`(${english})`)) {
      return `${match} (${english})`;
    }
    return match;
  });

  if (newText !== originalText) {
    textNode.textContent = newText;
    processedNodes.add(textNode);
  }
}

function walkTextNodes(element) {
  const walker = document.createTreeWalker(
    element,
    NodeFilter.SHOW_TEXT,
    {
      acceptNode: (node) => {
        // Skip script, style, and already processed nodes
        const parent = node.parentElement;
        if (!parent) return NodeFilter.FILTER_REJECT;
        const tagName = parent.tagName.toLowerCase();
        if (tagName === 'script' || tagName === 'style' || tagName === 'noscript') {
          return NodeFilter.FILTER_REJECT;
        }
        // Only process nodes with actual text content
        if (node.textContent.trim().length === 0) {
          return NodeFilter.FILTER_REJECT;
        }
        return NodeFilter.FILTER_ACCEPT;
      }
    }
  );

  const textNodes = [];
  while (walker.nextNode()) {
    textNodes.push(walker.currentNode);
  }

  textNodes.forEach(translateTextNode);
}

// Initial translation pass - paragon board rows and item sections
function initialTranslation() {
  // Translate paragon glyphs
  document.querySelectorAll('.d4para-row').forEach(row => {
    walkTextNodes(row);
  });

  // Translate items and aspects
  document.querySelectorAll('.d4-item').forEach(item => {
    walkTextNodes(item);
  });
}

// Observe DOM for dynamic content
function setupObserver() {
  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      // Handle added nodes - within .d4para-row or .d4-item elements
      mutation.addedNodes.forEach((node) => {
        if (node.nodeType === Node.ELEMENT_NODE) {
          // Check if node is a paragon row or item container
          if (node.classList?.contains('d4para-row') || node.classList?.contains('d4-item')) {
            walkTextNodes(node);
          }
          // Check if node is inside a paragon row or item container
          else if (node.closest('.d4para-row') || node.closest('.d4-item')) {
            walkTextNodes(node);
          }
          // Search for paragon rows or item containers within the node
          else if (node.querySelectorAll) {
            node.querySelectorAll('.d4para-row, .d4-item').forEach(element => walkTextNodes(element));
          }
        } else if (node.nodeType === Node.TEXT_NODE) {
          // Translate text nodes inside paragon rows or item containers
          if (node.parentElement?.closest('.d4para-row') || node.parentElement?.closest('.d4-item')) {
            translateTextNode(node);
          }
        }
      });

      // Handle character data changes - within .d4para-row or .d4-item elements
      if (mutation.type === 'characterData' && mutation.target.nodeType === Node.TEXT_NODE) {
        if (mutation.target.parentElement?.closest('.d4para-row') || mutation.target.parentElement?.closest('.d4-item')) {
          processedNodes.delete(mutation.target);
          translateTextNode(mutation.target);
        }
      }
    });
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true,
    characterData: true
  });
}

// Run when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => {
    initialTranslation();
    setupObserver();
  });
} else {
  initialTranslation();
  setupObserver();
}

console.log('D4 German Translator loaded - translating glyphs, items, aspects, and tempering recipes');
